### ISSUE TITLE
Unable To Move

### ISSUE THREAD

**Issue by jazzy348** [Professional-Hobo/PokeMMOn#1]
Tried on both an Android phone and Chrome, unable to move player.

**Comment by keitharm** [comment]
We've moved from making a clone of a Pokemon game, to making our own [game engine](https://github.com/HuskyEngine/Engine).

We are testing the game engine with Pokemon, but the source code for that implementation isn't readily available at the moment. You can play around with it [here ](https://keitharm.me/projects/huskyengine/)if you're interested.
